In [1]:
print('fit a model with', 11, 'variables')


fit a model with 11 variables


In [2]:
print?


Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [3]:
3 + 5


8

In [4]:
"hello" + " " + "world"


'hello world'

In [5]:
x = [3, 4, 5]
x


[3, 4, 5]

In [6]:
y = [4, 9, 7]
x + y


[3, 4, 5, 4, 9, 7]

  To access `numpy`, we must first `import` it.

In [7]:
import numpy as np 

In [8]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [9]:
x + y

array([ 7, 13, 12])

In [10]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [11]:
x.ndim

2

In [12]:
x.dtype

dtype('int32')

In [13]:
np.array([[1, 2], [3.0, 4]]).dtype


dtype('float64')

In [14]:
np.array?


Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [15]:
np.array([[1, 2], [3, 4]], float).dtype


dtype('float64')

In [16]:
x.shape


(2, 2)

In [17]:
x = np.array([1, 2, 3, 4])
x.sum()

10

In [18]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [19]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)


beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [20]:
x_reshape[0, 0] 

1

In [21]:
x_reshape[1, 2] 

6

In [22]:
print('x before we modify x_reshape:\n', x)
print('x_reshape before we modify x_reshape:\n', x_reshape)
x_reshape[0, 0] = 5
print('x_reshape after we modify its top left element:\n', x_reshape)
print('x after we modify top left element of x_reshape:\n', x)


x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


In [24]:
my_list = list(my_tuple)  # Convert tuple to list
my_list[0] = 2            # Modify the first element
print(my_list)            # Output: [2, 4, 5]


[2, 4, 5]


In [ ]:
x_reshape.shape, x_reshape.ndim, x_reshape.T


In [ ]:
np.sqrt(x)


We can also square the elements:

In [ ]:
x**2


In [ ]:
x**0.5


In [ ]:
x = np.random.normal(size=50)
x


In [ ]:
y = x + np.random.normal(loc=50, scale=1, size=50)

In [ ]:
np.corrcoef(x, y)

In [ ]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2)) 


In [ ]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2)) 

In [ ]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

In [ ]:
np.var(y), y.var(), np.mean((y - y.mean())**2)

In [ ]:
np.sqrt(np.var(y)), np.std(y)

In [ ]:
X = rng.standard_normal((10, 3))
X

In [ ]:
X.mean(axis=0)

In [ ]:
X.mean(0)

In [ ]:
from matplotlib.pyplot import subplots
fig, ax = subplots(figsize=(8, 8))
x = rng.standard_normal(100)
y = rng.standard_normal(100)
ax.plot(x, y);


In [ ]:
output = subplots(figsize=(8, 8))
fig = output[0]
ax = output[1]

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.plot(x, y, 'o');

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.scatter(x, y, marker='o');

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.scatter(x, y, marker='o')


In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.scatter(x, y, marker='o')
ax.set_xlabel("this is the x-axis")
ax.set_ylabel("this is the y-axis")
ax.set_title("Plot of X vs Y");

In [ ]:
fig.set_size_inches(12,3)
fig

In [ ]:
fig, axes = subplots(nrows=2,
                     ncols=3,
                     figsize=(15, 5))

In [ ]:
axes[0,1].plot(x, y, 'o')
axes[1,2].scatter(x, y, marker='+')
fig

In [ ]:
fig.savefig("Figure.png", dpi=400)
fig.savefig("Figure.pdf", dpi=200);


In [ ]:
axes[0,1].set_xlim([-1,1])
fig.savefig("Figure_updated.jpg")
fig

In [ ]:
fig, ax = subplots(figsize=(8, 8))
x = np.linspace(-np.pi, np.pi, 50)
y = x
f = np.multiply.outer(np.cos(y), 1 / (1 + x**2))
ax.contour(x, y, f);


In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.contour(x, y, f, levels=45);

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.imshow(f);


In [ ]:
seq1 = np.linspace(0, 10, 11)
seq1


In [ ]:
seq2 = np.arange(0, 10)
seq2


In [ ]:
"hello world"[3:6]

In [ ]:
"hello world"[slice(3,6)]


In [ ]:
A = np.array(np.arange(16)).reshape((4, 4))
A


In [ ]:
A[1,2]


In [ ]:
A[[1,3]]


In [ ]:
A[:,[0,2]]


In [ ]:
A[[1,3],[0,2]]


In [ ]:
np.array([A[1,0],A[3,2]])


In [ ]:
A[[1,3],[0,2,3]]


In [ ]:
A[[1,3]][:,[0,2]]


In [ ]:
idx = np.ix_([1,3],[0,2,3])
A[idx]


In [ ]:
A[1:4:2,0:3:2]


In [ ]:
keep_rows = np.zeros(A.shape[0], bool)
keep_rows

We now set two of the elements to `True`. 

In [ ]:
keep_rows[[1,3]] = True
keep_rows


In [ ]:
np.all(keep_rows == np.array([0,1,0,1]))


In [ ]:
A[np.array([0,1,0,1])]


In [ ]:
A[keep_rows]


In [ ]:
keep_cols = np.zeros(A.shape[1], bool)
keep_cols[[0, 2, 3]] = True
idx_bool = np.ix_(keep_rows, keep_cols)
A[idx_bool]


In [ ]:
idx_mixed = np.ix_([1,3], keep_cols)
A[idx_mixed]


In [ ]:
import pandas as pd
Auto = pd.read_csv('Auto.csv')
Auto


In [ ]:
Auto = pd.read_csv('Auto.data', delim_whitespace=True)


In [ ]:
Auto['horsepower']


In [ ]:
np.unique(Auto['horsepower'])


In [ ]:
Auto = pd.read_csv('Auto.data',
                   na_values=['?'],
                   delim_whitespace=True)
Auto['horsepower'].sum()


In [ ]:
Auto.shape


In [ ]:
Auto_new = Auto.dropna()
Auto_new.shape


In [ ]:
Auto[:3]


In [ ]:
idx_80 = Auto['year'] > 80
Auto[idx_80]


In [ ]:
Auto[['mpg', 'horsepower']]


In [ ]:
Auto.index


In [ ]:
Auto_re = Auto.set_index('name')
Auto_re


In [ ]:
Auto_re.columns


In [ ]:
rows = ['amc rebel sst', 'ford torino']
Auto_re.loc[rows]


In [ ]:
Auto_re.iloc[[3,4]]


In [ ]:
Auto_re.iloc[:,[0,2,3]]


In [ ]:
Auto_re.iloc[[3,4],[0,2,3]]


In [ ]:
Auto_re.loc['ford galaxie 500', ['mpg', 'origin']]


In [ ]:
idx_80 = Auto_re['year'] > 80
Auto_re.loc[idx_80, ['weight', 'origin']]


In [ ]:
Auto_re.loc[lambda df: df['year'] > 80, ['weight', 'origin']]


In [ ]:
Auto_re.loc[lambda df: (df['year'] > 80) & (df['mpg'] > 30),
            ['weight', 'origin']
           ]


In [ ]:
Auto_re.loc[lambda df: (df['displacement'] < 300)
                       & (df.index.str.contains('ford')
                       | df.index.str.contains('datsun')),
            ['weight', 'origin']
           ]


In [ ]:
total = 0
for value in [3,2,19]:
    total += value
print('Total is: {0}'.format(total))


In [ ]:
total = 0
for value in [2,3,19]:
    for weight in [3, 2, 1]:
        total += value * weight
print('Total is: {0}'.format(total))

In [ ]:
total = 0
for value, weight in zip([2,3,19],
                         [0.2,0.3,0.5]):
    total += weight * value
print('Weighted average is: {0}'.format(total))


In [ ]:
rng = np.random.default_rng(1)
A = rng.standard_normal((127, 5))
M = rng.choice([0, np.nan], p=[0.8,0.2], size=A.shape)
A += M
D = pd.DataFrame(A, columns=['food',
                             'bar',
                             'pickle',
                             'snack',
                             'popcorn'])
D[:3]


In [ ]:
for col in D.columns:
    template = 'Column "{0}" has {1:.2%} missing values'
    print(template.format(col,
          np.isnan(D[col]).mean()))


In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.plot(horsepower, mpg, 'o');

We can address this by accessing the columns directly:

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.plot(Auto['horsepower'], Auto['mpg'], 'o');


Alternatively, we can use the `plot()` method with the call `Auto.plot()`.
Using this method,
the variables  can be accessed by name.
The plot methods of a data frame return a familiar object:
an axes. We can use it to update the plot as we did previously: 

In [ ]:
ax = Auto.plot.scatter('horsepower', 'mpg')
ax.set_title('Horsepower vs. MPG');

In [ ]:
fig = ax.figure
fig.savefig('horsepower_mpg.png');

In [ ]:
fig, axes = subplots(ncols=3, figsize=(15, 5))
Auto.plot.scatter('horsepower', 'mpg', ax=axes[1]);


In [ ]:
Auto.cylinders = pd.Series(Auto.cylinders, dtype='category')
Auto.cylinders.dtype


In [ ]:
fig, ax = subplots(figsize=(8, 8))
Auto.boxplot('mpg', by='cylinders', ax=ax);


In [ ]:
fig, ax = subplots(figsize=(8, 8))
Auto.hist('mpg', ax=ax);


In [ ]:
fig, ax = subplots(figsize=(8, 8))
Auto.hist('mpg', color='red', bins=12, ax=ax);


In [ ]:
pd.plotting.scatter_matrix(Auto);


 We can also produce scatterplots
for a subset of the variables.

In [ ]:
pd.plotting.scatter_matrix(Auto[['mpg',
                                 'displacement',
                                 'weight']]);


In [ ]:
Auto[['mpg', 'weight']].describe()


In [ ]:
Auto['cylinders'].describe()
Auto['mpg'].describe()
